using System;
namespace SampleConApp
{
    class ExceptionDemo
    {
        static void simpleDemo()
        {
        RETRY:
            Console.WriteLine("Enter a number");
            try
            {
                int no = int.Parse(Console.ReadLine());
                Console.WriteLine("The value entered is " + no);
            }
            catch (FormatException)
            {
                Console.WriteLine("Only numbers should be entered");
                goto RETRY;
            }
            catch (OverflowException)
            {
                Console.WriteLine("Number entered is either too large or too small to store");
                goto RETRY;
            }
            catch (Exception ex)
            {
                Console.WriteLine("OOPS! Something wrong happened.");
                Console.WriteLine(ex.Message);//Message generated by the System when this Exception was raised....
                goto RETRY;
            }
            finally
            {
                Console.WriteLine("End of the Program");
            }
        }
        static void Main(string[] args)
        {
            //simpleDemo();
            customExceptionDemo();
        }

        private static void customExceptionDemo()
        {
            throw new NotImplementedException();
        }
    }
}